/*
DROP TABLE sequence;
DROP TABLE CCD_LINE_ITEM;
DROP TABLE CCD_ITEM;
DROP TABLE CCD_SUB_CATEGORY;
DROP TABLE CCD_CATEGORY; 
DROP TABLE CCD_ORDER_STATUS;
DROP TABLE CCD_STATUS_INFO;
DROP TABLE CCD_ORDERS;
DROP TABLE CCD_ACCOUNT;
DROP TABLE CCD_SIGNON;
*/

CREATE TABLE CCD_ACCOUNT (
 USER_ID 			VARCHAR(30) NOT NULL,
 PREFIX			VARCHAR(20),
 FIRST_NAME			VARCHAR(50) NOT NULL,
 LAST_NAME 			VARCHAR(50) NOT NULL,
 EMAIL 			VARCHAR(80),
 PHONE 			VARCHAR(50),
 PHONE_LAB 			VARCHAR(50),
 FAX 				VARCHAR(80),
 COMPANY			VARCHAR(150),
 CATEGORY 			VARCHAR(100),
 TITLE			VARCHAR(100),
 ADDR1 			VARCHAR(80),
 ADDR2 			VARCHAR(40),
 CITY				VARCHAR(80),
 PROV_STATE			VARCHAR(80),
 POSTAL_ZIP			VARCHAR(20),
 COUNTRY 			VARCHAR(20),
 FEDEX 			VARCHAR(15),
 LANG_PREF			VARCHAR(20),
 LAST_REFRESH		DATE,
 SYS_CREATION_DATE 	DATE,
 SYS_UPDATE_DATE		DATE,
 SYS_CREATED_BY		VARCHAR(50),
 SYS_UPDATED_BY		VARCHAR(50),
 CONSTRAINT PK_ACCOUNT PRIMARY KEY (USER_ID)
);


CREATE TABLE CCD_CATEGORY (
 CATEGORY_ID		VARCHAR(50) NOT NULL,
 CATEGORY_NAME		VARCHAR(100) NOT NULL,
 CATEGORY_DESC		VARCHAR(100),
 SYS_CREATION_DATE 	DATE,
 SYS_UPDATE_DATE		DATE,
 SYS_CREATED_BY		VARCHAR(50),
 SYS_UPDATED_BY		VARCHAR(50),
 CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE CCD_SUB_CATEGORY (
 SUB_CATEGORY_ID		VARCHAR(50) NOT NULL,
 SUB_CATEGORY_NAME	VARCHAR(100) NOT NULL,
 SUB_CATEGORY_DESC	VARCHAR(100),
 CATEGORY_ID		VARCHAR(50) NOT NULL,
 SYS_CREATION_DATE 	DATE,
 SYS_UPDATE_DATE		DATE,
 SYS_CREATED_BY		VARCHAR(50),
 SYS_UPDATED_BY		VARCHAR(50),
 CONSTRAINT PK_SUB_CATEGORY PRIMARY KEY (SUB_CATEGORY_ID),
 CONSTRAINT SUB_TO_CATEGORY FOREIGN KEY (CATEGORY_ID)
            REFERENCES CCD_CATEGORY (CATEGORY_ID)
);



CREATE TABLE CCD_ITEM (
 ITEM_ID 			int NOT NULL,
 SUB_CATEGORY_ID		VARCHAR(50) NOT NULL,
 CATEGORY_ID		VARCHAR(50) NOT NULL,
 NAME 			VARCHAR(80),
 UNIT_PRICE			decimal(10,2),
 UNIT	 			VARCHAR(50),
 STATUS 			VARCHAR(2),
 PROD_IND			VARCHAR(50), 
 AVAIL_FLAG			VARCHAR(10), 
 CHAR_ATTR1 			VARCHAR(100),
 CHAR_ATTR2 			VARCHAR(100),
 CHAR_ATTR3 			VARCHAR(100),
 CHAR_ATTR4 			VARCHAR(100),
 CHAR_ATTR5 			VARCHAR(100),
 CHAR_ATTR6 			VARCHAR(100),
 CHAR_ATTR7 			VARCHAR(100),
 CHAR_ATTR8 			VARCHAR(100),
 CHAR_ATTR9 			VARCHAR(100),
 NUMBER_ATTR1 			decimal(10,2),
 NUMBER_ATTR2 			decimal(10,2),
 NUMBER_ATTR3 			decimal(10,2),
 NUMBER_ATTR4 			decimal(10,2),
 NUMBER_ATTR5 			decimal(10,2),
 DATE_ATTR1 			DATE,
 DATE_ATTR2 			DATE,
 SYS_CREATION_DATE 	DATE,
 SYS_UPDATE_DATE		DATE,
 SYS_CREATED_BY		VARCHAR(50),
 SYS_UPDATED_BY		VARCHAR(50),
 CONSTRAINT PK_ITEM PRIMARY KEY (ITEM_ID),
 CONSTRAINT ITEM_TO_SUBCAT FOREIGN KEY (SUB_CATEGORY_ID)
            REFERENCES CCD_SUB_CATEGORY (SUB_CATEGORY_ID)
);




CREATE TABLE CCD_ORDERS (
 ORDER_ID 			int NOT NULL,
 USER_ID 			VARCHAR(80) NOT NULL,
 ORDER_DATE 		DATE NOT NULL,
 WEB_STATUS			VARCHAR(10),  
 SHIP_ADDR1 		VARCHAR(80) NOT NULL,
 SHIP_ADDR2 		VARCHAR(80),
 SHIP_CITY 			VARCHAR(80) NOT NULL,
 SHIP_PROV_STATE 		VARCHAR(80) NOT NULL,
 SHIP_POSTAL_ZIP		VARCHAR(20) NOT NULL,
 SHIP_COUNTRY 		VARCHAR(20) NOT NULL,
 FEDEX 			VARCHAR(80) NOT NULL,
 TOTAL_PRICE 		decimal(10,2),
 SHIPTO_FIRST_NAME	VARCHAR(80) NOT NULL,
 SHIPTO_LAST_NAME 	VARCHAR(80) NOT NULL,
 COMMENTS		VARCHAR(2000), 
 SYS_CREATION_DATE 	DATE,
 SYS_UPDATE_DATE		DATE,
 SYS_CREATED_BY		VARCHAR(50),
 SYS_UPDATED_BY		VARCHAR(50),
 CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
 CONSTRAINT ORDERED_BY FOREIGN KEY (USER_ID)
            REFERENCES CCD_ACCOUNT (USER_ID)
);



CREATE TABLE CCD_LINE_ITEM (
 ORDER_ID 			int NOT NULL,
 LINENUM 			int NOT NULL,
 ITEM_ID 			int NOT NULL,
 QUANTITY 			decimal(10,2),
 PRICE			decimal(10,2),
 SYS_CREATION_DATE 	DATE,
 SYS_UPDATE_DATE		DATE,
 SYS_CREATED_BY		VARCHAR(50),
 SYS_UPDATED_BY		VARCHAR(50),
 CONSTRAINT PK_LINEITEM PRIMARY KEY (ORDER_ID, LINENUM),
 CONSTRAINT ITEM_ORDERD_ON FOREIGN KEY (ORDER_ID)  REFERENCES CCD_ORDERS (ORDER_ID) ON DELETE CASCADE,
 CONSTRAINT ORDER_FOR_ITEM FOREIGN KEY (ITEM_ID) REFERENCES CCD_ITEM (ITEM_ID)
 );


CREATE TABLE CCD_STATUS_INFO (       
 STATUS_CODE		int NOT NULL,
 STATUS_DESC		VARCHAR(100) NOT NULL,
 SYS_CREATION_DATE 	DATE,
 SYS_UPDATE_DATE		DATE,
 SYS_CREATED_BY		VARCHAR(50),
 SYS_UPDATED_BY		VARCHAR(50),
 CONSTRAINT PK_STATUS_CODE PRIMARY KEY (STATUS_CODE)
);


CREATE TABLE CCD_ORDER_STATUS (
 ORDER_ID 			int NOT NULL,
 LINENUM 			int NOT NULL,
 lAST_CHANGE_DATE		DATE NOT NULL,
 STATUS_CODE		int NOT NULL,
 SYS_CREATION_DATE 	DATE,
 SYS_UPDATE_DATE		DATE,
 SYS_CREATED_BY		VARCHAR(50),
 SYS_UPDATED_BY		VARCHAR(50),
 CONSTRAINT PK_ORDERSTATUS PRIMARY KEY (ORDER_ID, LINENUM),
 CONSTRAINT STATUS_OF_ORDER FOREIGN KEY (ORDER_ID) REFERENCES CCD_ORDERS (ORDER_ID) ON DELETE CASCADE,
 CONSTRAINT ORDER_STATUS_HAS_DESC FOREIGN KEY (STATUS_CODE) REFERENCES CCD_STATUS_INFO (STATUS_CODE)
);


CREATE TABLE CCD_SIGNON (
 USER_ID 			VARCHAR(80) NOT NULL,
 PASSWORD 			VARCHAR(25) NOT NULL,
 SYS_CREATION_DATE 	DATE,
 SYS_UPDATE_DATE		DATE,
 SYS_CREATED_BY		VARCHAR(50),
 SYS_UPDATED_BY		VARCHAR(50),
 CONSTRAINT PK_SIGNON PRIMARY KEY (USER_ID)
);


CREATE TABLE sequence
(
    name               varchar(30)  not null,
    nextid             int          not null,
    constraint pk_sequence primary key (name)
);

INSERT INTO sequence VALUES('ordernum', 1000);
INSERT INTO sequence VALUES('linenum', 1000);

commit;
