alter table po_item drop constraint fk_item_product;
alter table po_item_supplied drop constraint fk_itemsupplied_item;
alter table po_item_supplied drop constraint fk_itemsupplied_supplier;
alter table po_user_role drop constraint FKA85ECA2AF73AEE0F;
alter table po_purchase_order drop constraint fk_purchase_order_lab;
alter table po_purchase_order drop constraint fk_purchase_order_user;
alter table po_product drop constraint fk_product_category;
alter table po_user_lab drop constraint FK56E5159F73AEE0F;
alter table po_user_lab drop constraint FK56E5159BDD0490D;
alter table po_lineitem drop constraint FK5C2E834765E2F5B;
alter table po_lineitem drop constraint fk_lineitem_item;
alter table po_lineitem drop constraint fk_lineitem_supplier;
drop table po_user if exists;
drop table po_lab if exists;
drop table po_item if exists;
drop table po_item_supplied if exists;
drop table po_supplier if exists;
drop table po_user_role if exists;
drop table po_category if exists;
drop table po_purchase_order if exists;
drop table po_product if exists;
drop table po_user_lab if exists;
drop table po_lineitem if exists;
create table po_user (
   id bigint generated by default as identity (start with 1),
   version integer not null,
   password varchar(30) not null,
   email varchar(80) not null,
   firstName varchar(50) not null,
   lastName varchar(50) not null,
   phoneNumber varchar(50),
   enabled bit,
   createdDate timestamp,
   createdBy varchar(50),
   updatedBy varchar(50),
   updatedDate timestamp,
   name varchar(50) not null,
   description varchar(100),
   unique (name)
);
create table po_lab (
   id bigint generated by default as identity (start with 1),
   name varchar(50) not null,
   description varchar(100),
   unique (name)
);
create table po_item (
   id bigint generated by default as identity (start with 1),
   version integer not null,
   name varchar(100) not null,
   description varchar(100),
   itemNumber varchar(50),
   distributor varchar(50),
   format varchar(50),
   manufacturer varchar(50),
   product_id bigint not null,
   listprice_amt Decimal(10,2),
   listprice_currency varchar(3),
   createdBy varchar(50),
   createdDate timestamp,
   updatedBy varchar(50),
   updatedDate timestamp
);
create table po_item_supplied (
   item_supplied_id bigint generated by default as identity (start with 1),
   catalogNumber varchar(30),
   bidInfo varchar(100),
   bidYear varchar(4),
   supplier_id bigint not null,
   item_id bigint not null,
   createdDate timestamp
);
create table po_supplier (
   id bigint generated by default as identity (start with 1),
   createdDate timestamp,
   createdBy varchar(50),
   salesrep_contact varchar(100),
   salesrep_name varchar(50),
   name varchar(50) not null,
   description varchar(100),
   unique (name)
);
create table po_user_role (
   user_id bigint not null,
   role varchar(255)
);
create table po_category (
   id bigint generated by default as identity (start with 1),
   createdBy varchar(50),
   createdDate timestamp,
   name varchar(50) not null,
   description varchar(100),
   unique (name)
);
create table po_purchase_order (
   po_id bigint generated by default as identity (start with 1),
   version integer not null,
   confirmNumber varchar(30),
   estimated_CAD_tot Decimal(10,2),
   effective_CAD_tot Decimal(10,2),
   effective_CAD_tax Decimal(10,2),
   orderFor varchar(30),
   lab_id bigint not null,
   user_id bigint not null,
   project varchar(100),
   payment_type varchar(50),
   current_status varchar(30),
   current_status_date timestamp,
   openDate timestamp,
   est_reception_date timestamp
);
create table po_product (
   id bigint generated by default as identity (start with 1),
   category_id bigint not null,
   createdBy varchar(50),
   createdDate timestamp,
   name varchar(50) not null,
   description varchar(100),
   unique (name)
);
create table po_user_lab (
   user_id bigint not null,
   lab_id bigint not null,
   primary key (user_id, lab_id)
);
create table po_lineitem (
   po_id bigint not null,
   item_id bigint not null,
   quantity integer not null,
   listprice_amt Decimal(10,2),
   listprice_currency varchar(3),
   supplier_id bigint not null,
   linenum integer not null,
   primary key (po_id, linenum)
);
alter table po_item add constraint fk_item_product foreign key (product_id) references po_product;
alter table po_item_supplied add constraint fk_itemsupplied_item foreign key (item_id) references po_item;
alter table po_item_supplied add constraint fk_itemsupplied_supplier foreign key (supplier_id) references po_supplier;
alter table po_user_role add constraint FKA85ECA2AF73AEE0F foreign key (user_id) references po_user;
alter table po_purchase_order add constraint fk_purchase_order_lab foreign key (lab_id) references po_lab;
alter table po_purchase_order add constraint fk_purchase_order_user foreign key (user_id) references po_user;
alter table po_product add constraint fk_product_category foreign key (category_id) references po_category;
alter table po_user_lab add constraint FK56E5159F73AEE0F foreign key (user_id) references po_user;
alter table po_user_lab add constraint FK56E5159BDD0490D foreign key (lab_id) references po_lab;
alter table po_lineitem add constraint FK5C2E834765E2F5B foreign key (po_id) references po_purchase_order;
alter table po_lineitem add constraint fk_lineitem_item foreign key (item_id) references po_item;
alter table po_lineitem add constraint fk_lineitem_supplier foreign key (supplier_id) references po_supplier;
